package controlFlow;

public class CartaForbiceSasso {

	public static void main(String[] args) {
		//TODO 1.18. EsercizioScrivere un programma che chieda agli utenti due stringhe in ingresso, le stringhe possono valere solo:“carta”, “forbice” o “sasso”.Il programma dovrà quindi effettuare i dovuti controlli e dichiarare il vincitore secondo le regole:
				//	forbice vince su carta,carta vince su sasso,sasso vince su forbice.1.19. EsercizioScrivere una funzione per calcolare l’importo di una tassa secondo la seguente tabella:Fino a 10.000 €, l’importo della tassa è del 10%Fino a 20.000 €, l’importo della tassa è del 10% per i primi 10.000 €, del 7 % sul restante.Fino a 30.000 €, l’importo è ancora del 10% per i primi 10.000 €, poi del 7% fino a 20.000 ed infine il5% sul restante.Oltre i 30.000 € ci si comporta come prima, aggiungendo un ulteriore 3% è sulla porzione oltre i30.000 €.Per ogni importo non valido si ritorni -1 (qualunque importo che non sia un numero reale e positivo).Esempi:Un importo di 10, dovrebbe tornare 1 (1 è il 10% di 10)Un importo di 21, dovrebbe tornare 1.75 (10% di 10 + 7% di 10 + 5% di 1)1.20. EsercizioScrivere un programma IndovinaZero che chiede all’utente di inserire numeri interi uno dopo l’altro fino aquando non inserisce il numero 0.1.21. EsercizioScrivere un programma ScrivoScrivoScrivo che chiede all’utente di inserire un numero maggiore o uguale azero e stampa il messaggio sto ciclando un numero di volte pari al numero inserito dall’utente. Se il valoreinserito dall’utente è negativo il programma stampa un messaggio di errore.1.22. EsercizioScrivere un programma Conteggio che chiede all’utente di inserire un numero maggiore o uguale a zero estampa uno dopo l’altro tutti i numeri da 0 al numero inserito compreso. Se il valore inserito dall’utente ènegativo il programma stampa un messaggio di errore.1.23. EsercizioScrivere un programma ContaNumeriCrescenti che chiede all’utente di inserire una sequenza di numeriinteri crescenti (man mano sempre più grandi) e ne stampa la lunghezza (il numero di valori inseritidall’utente). Il programma termina non appena l’utente inserisce un valore minore o uguale al precedente).
				// EsercizioScrivere un programma MediaNumeri che chiede all’utente di inserire una sequenza di numeri interipositivi. Non appena l’utente inserisce un numero negativo il programma si arresta e visualizza la mediaaritmetica dei valori positivi inseriti (senza approssimazione!).1.25. EsercizioScrivere un programma Asterischi che chiede all’utente di inserire un numero intero e stampa un triangolofatto di asterischi con un numero di righe pari al valore inserito dall’utente. Se l’utente inserisce un valorenegativo il programma deve visualizzare un messaggio di errore.1.26. EsercizioScrivere un programma TavolaPitagorica in modo che i valori stampati siano ben incolonnati

				
	}

}
